// Importing the createSlice function from the "@reduxjs/toolkit" library
import { createSlice } from "@reduxjs/toolkit";

// Creating a slice for user-related state management
const userSlice = createSlice({
    // Name of the slice, helps in generating action types
    name : 'user',
    // Initial state for the user slice, set to null initially
    initialState: null,
    // Reducer functions to handle state changes
    reducers: {
        // Reducer to add a user to the state
        addUser : (state, action)=>{
            return action.payload
        },
        // Reducer to remove a user from the state
        removeUser : ()=>{
            return null;
        }
    }
})

// Exporting the reducer function generated by createSlice
export default userSlice.reducer;
// Exporting action creators for the addUser and removeUser reducers
export const { addUser, removeUser } = userSlice.actions